### ISSUE TITLE
Issue with auto scroll 

### ISSUE THREAD

**Issue by trishtracking** [fac20/Week9-DEKN#46]
The idea of posting and then auto scrolling down to the posts is really cool (I think that's what you were trying to do?) 

However, it's giving me an error (netlify version) : 

Uncaught TypeError: Failed to execute 'scrollTo' on 'Window': parameter 1 ('options') is not an object.
    at HTMLButtonElement.onclick (app.js:198)
app.js:217

**Comment by jhart5** [comment]
This may be because your arguments for window.scrollTo are inside quotes. It should just take numbers as arguments. Not 100% sure though
